### PR TITLE
Set margin of overlay to padding of element

### PR DESCRIPTION
**Pull request by blainsmith**
I ran into an issue where I was using a large padding and the overlay was not covering exactly what I wanted. So by setting the margin of the overlay to the elements padding it fixed the issue.

screen shot 2014-11-12 at 9 54 34 am

### CODE REVIEW

**Comment by ellekasai** [comment]
Thank you so much for your pull request, and I'm sorry for my late reply. I've been very busy for the past few days since I released purplecoat.js. And I'll be attending startup week vancouver (http://www.startupweekvancouver.ca/) full time until 11/21. I promise to take a look at your pull request closely after that's over. Hope you don't mind!

**Comment by blainsmith** [comment]
Absolutely no rush. Thanks for checking in though! Enjoy Startup Week!

**Comment by ellekasai** [comment]
I ended up fixing this by using outerWidth()/outerHeight() instead of width()/height() - I think this fix makes more sense than adding margin. Thanks for the pull request though!

https://github.com/ellekasai/purplecoat.js/pull/14

**Comment by blainsmith** [comment]
Brilliant! Love it, thanks!

**Pull request closed without merging**
