### PR TITLE
purplecoatToggle function

### PR DESCRIPTION
**Pull request by codler**
Extracted existing code to a purplecoatToggle function.
This allows you to programmatically toggle a set of purplecoat
Usage example

``` javascript
purplecoatToggle('odd')
```

### CODE REVIEW

**Comment by ellekasai** [comment]
Thank you so much for your pull request, and I'm sorry for my late reply. I've been very busy for the past few days since I released purplecoat.js. And I'll be attending startup week vancouver (http://www.startupweekvancouver.ca/) full time until 11/21. I promise to take a look at your pull request closely after that's over. Hope you don't mind!

**Comment by codler** [comment]
Nice, no need to rush.

**Comment by ellekasai** [comment]
Hi, I decided to turn this into a simple jQuery plugin, which should cover your use case. Please take a look at http://ellekasai.github.io/purplecoat.js/#jquery-api

Thanks!

**Comment by codler** [comment]
:+1: great!

**Pull request closed without merging**
